server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eyedaero
    username: root
    password: "0304"
# url:
#    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        format_sql: true
    open-in-view: false

#jwt:
#  secretKey: wpdlejqmfdbxl
#  accessExpiration: 300000
#  refreshExpiration: 600000
#  aesKey: aesEncryptKeyeee
#
#jasypt:
#  encryptor:
#    password: ${JASYPT_ENCRYPTOR_PASSWORD}

#
#cloud:
#  aws:
#    s3:
#      bucket: ${storage_name}
#    stack.auto: false
#    region.static: ap-northeast-2
#    credentials:
#      accessKey: ${storage_access_key}
#      secretKey: ${storage_secret_key}